- src/app/basketball-mate/page.tsx
- src/app/components/Footer.tsx
- src/app/components/Header.tsx
- src/app/matching/page.tsx
- src/app/page.tsx
- src/app/team-matching/page.tsx
> MAI-41,42 헤더,푸터 네비게이터 버튼 링크 추가

- src/app/map/CourtDetail.tsx
- src/app/map/KakaoMap.tsx
> 전화번호 표시, 위치 정보 error 알림
- 실제 정보 받기, 기타 정보 수정시 저장 -> api 개발 완료시 연결 필요
resolved: #23
> #23 농구장 상세정보 - 전화번호 표시, 위치 정보 error 알림

- src/app/components/Header.tsx
- src/app/layout.tsx
- src/app/page.tsx
> refactor: 헤더 css 수정

- package-lock.json
- package.json
- src/app/api/axiosInstance.ts
- src/store/authStore.ts
> 백엔드 담당자와 얘기 후 axiosInstance 설정했습니다.
- 토큰 refresh 요청시 401 실패 에러를 받으면 로그아웃되도록 처리했습니다. 로그아웃시 로그인 페이지로 이동하는 로직은 지금은 필요하지 않아 임시 주석 처리 해놨습니다.
- '/api/token/refresh' 경로 추후 변경될 수 있음
> #37 axiosInstance 설정

- src/app/(auth)/login/email/page.tsx
- src/app/(auth)/user-info/page.tsx
- src/app/components/Header.tsx
- src/store/authStore.ts
> 자체 회원가입, 로그인 구현 완료됨에 따라 로그인 상태 추가했습니다.
> zustand 이용 전역변수로 accessToken 저장, 로그인 상태 관리
> 현재 백엔드 로직이 회원가입 후 자동 로그인이 아니라 회원가입 후 로그인을 해줘야 합니다. 추후 변경될 수 있습니다.
> 로그아웃 추가 예정입니다. 
> 헤더 아이콘은 추후 변경 예정입니다.
> #52 로그인 상태 추가

- src/app/components/Header.tsx
> refactor: hydration 오류 임시 주석 처리
> #55 hydration 오류 임시 주석 처리

- src/app/matching/components/KakaoMapModal.tsx
- src/app/matching/mate-new-post/page.tsx
> 메이트 매칭 새 모집글 작성 폼 UI 수정

- src/app/matching/components/MateMatching.tsx
- src/app/matching/components/TeamMatching.tsx
- src/app/matching/team-new-post/page.tsx
- 메이트 찾기 양식이랑 거의 동일하게 작성하여서 특이사항 없습니다!
> #80 TEA-71 상대팀 찾기 새 모집글 작성 폼 구현

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
- src/app/chatting/list/page.tsx
- src/app/community/[tag]/layout.tsx
> #86 style: 회색색상 변경

- src/app/chatting/chatroom/[roomId]/page.tsx
> 현재 채팅 룸 1 주소가 정해져있고, 서로 다른 유저가 같은 채팅룸에 접속하는 테스트까지 완료했습니다.
resovled #63
> #63 CHA-51 채팅 소켓 연결

- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/my-page/profile/page.tsx
- src/app/(auth)/my-page/settings/page.tsx
> 헤더 아이콘 위치 수정, 마이페이지 뒤로가기 추가
- 👀 같이 리뷰 필요
>  (마이 페이지 뒤로가기 추가(top 20px, left 20px로 고정) -> 로그인 부분에 있는 뒤로가기도 추후 스타일 수정하겠습니다. 뒤로가기 모두 top 20px, left 20px 위치에 고정시키면 좋을 것 같은데 어떤가요?)
-> ✅ 회의로 기본 16px(p-4)로 사용하기로 했습니다!
> 프로필 페이지 추후 구현 예정
> #46 style: 마이페이지 뒤로가기 추가, 위치 수정

- src/app/(auth)/login/email/page.tsx
- src/app/(auth)/login/layout.tsx
- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/signup/layout.tsx
- src/app/(auth)/signup/page.tsx
- src/services/user/getUserData.ts
- src/types/user/userInfo.ts
> 팀 컨벤션에 맞춰 UI 수정,  마이페이지 - 관리자 페이지 이동 버튼 추가
> #111 팀 컨벤션에 맞춰 UI 수정,  마이페이지 - 관리자 페이지 이동 버튼 추가

- src/app/matching/components/MatchingHeader.tsx
- src/app/matching/components/MateMatching.tsx
- src/app/matching/components/MatePostCard.tsx
- src/app/matching/components/TeamApplicantList.tsx
- src/app/matching/components/TeamMatching.tsx
- src/app/matching/components/TeamPostCard.tsx
- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/mate-details/[postId]/revise/page.tsx
- src/app/matching/mate-new-post/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
- src/app/matching/team-details/[postId]/revise/page.tsx
- src/app/matching/team-new-post/page.tsx
- src/types/matching/mateDataType.ts
- src/types/matching/teamDataType.ts
> #96 API 변경에 따른 코드 수정

- src/app/map/components/CourtReport.tsx
- src/app/map/components/KakaoMap.tsx
> 농구장 api 요청 성공, 실패 alert 추가, 제보 완료 후 제보한 마커 삭제, 모달 닫기, 제보 모드 false
> #108 농구장 제보 API 응답 alert 작성, 제보 완료 후 처리

- src/app/matching/components/TeamMatching.tsx
- src/app/matching/page.tsx
> #96 상대팀 찾기 검색어 필터 추가

- src/app/community/[tag]/page.tsx
- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
> 게시글 및 댓글 작성자와 로그인한 유저가 동일할 때만 수정,삭제 가능하게하기
> #136 커뮤니티 게시글,댓글 수정,삭제 권한 나누기

- src/app/components/MiniMatePostCard.tsx
- src/app/components/MiniTeamPostCard.tsx
- src/app/matching/components/MatchingHeader.tsx
- src/app/matching/components/MateMatching.tsx
- src/app/matching/components/TeamMatching.tsx
- src/app/matching/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
- src/app/page.tsx
- src/services/home/getSchedule.ts
- src/services/matching/getMateData.ts
- src/services/matching/getTeamData.ts
- src/types/home/scheduleType.ts
> #97 메인페이지 DB 데이터 연결 작업

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
- src/app/chatting/list/page.tsx
- src/app/community/[tag]/page.tsx
- src/services/chatting/getChatList.ts
- src/types/chat/chatRoomListItem.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.
- 더보기 요청 시 채팅을 진행한 상태에서만 정상 작동하는 점에 대해 수정중
> #142 채팅방 나가기 및 과거 내역 더보기 추가

- src/app/chatting/chatroom/[roomId]/page.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.
- 배포 환경에서 환경변수 등록후 이전에 brokerURL 방식으로 재시도 합니다.
> #142 배포환경에서 채팅실행

- src/app/community/[tag]/page.tsx
- src/services/community/getCommunityTag.ts
> 삭제했던 게시판 태그 필터 기능 추가
- api로 불러오는 과정에서 에러가 발생해서 기능 완성이 우선이라 판단하여, 프론트 엔드에서 분류하게 구현했습니다. 해당 부분은 다른 기능 완성후에 리팩토링 하도록 하겠습니다.
> #140 커뮤니티 태그별 분류

- src/app/components/UserProfile.tsx
- src/app/user/page.tsx
> 상대방 프로필 Next UI Modal로 수정
> 프로필 존재 페이지에 모달 연결 필요
> #122 style: 상대방 프로필 Next UI Modal로 수정

- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/mate-new-post/page.tsx
> #152 메이트 찾기 모집 완료시 채팅방 생성

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.
resolved: #142 #146
> #142 채팅방 추가내역 불러오기, 퇴장 모달 경고창 추가

- src/app/(auth)/login/email/page.tsx
- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/my-page/settings/page.tsx
- src/app/(auth)/social-login/page.tsx
- src/app/components/Header.tsx
- src/app/components/UserProfile.tsx
- src/app/layout.tsx
- src/app/map/components/CourtReport.tsx
> 모바일 환경에서 확인한 결과 모달 placement='center'로 가운데에 기본 사이즈로 띄우는 것이 제일 괜찮아 보입니다!
> 많이 노출되는 알림부터 모달로 변경해나가면 좋을 것 같습니다.
> 
> [참고](https://nextui.org/docs/components/modal)
> #122 상대방 프로필 1:1 채팅 연결, 헤더 수정, 로그아웃 모달 추가

- src/app/layout.tsx
- src/styles/globals.css
> 멘토링 피드백에 따른 폰트 적용 완료 했습니다.
[참고](https://github.com/orioncactus/pretendard?tab=readme-ov-file)
> #162 style: Pretendard 폰트 적용

- src/app/admin/components/AdminCourtDetails.tsx
- src/app/admin/components/adminDataType.ts
> #127 농구장 제보 승인시 농구장 채팅방 생성

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
- src/app/chatting/list/page.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능).
- 추가 수정 부분은 pr 후에 적용할 예정입니다.
> #166 채팅방 에러 수정

- package-lock.json
- src/app/components/MiniMatePostCard.tsx
- src/app/components/MiniTeamPostCard.tsx
- src/app/matching/components/MateApplicantList.tsx
- src/app/matching/components/MateMatching.tsx
- src/app/matching/components/TeamApplicantList.tsx
- src/app/matching/components/TeamMatching.tsx
- src/app/matching/layout.tsx
- src/app/matching/mate-details/[postId]/layout.tsx
- src/app/matching/page.tsx
- src/app/matching/team-details/[postId]/layout.tsx
- src/app/page.tsx
> #171 메인페이지 반응형 수정

- src/app/matching/layout.tsx
- src/app/matching/mate-details/[postId]/application/page.tsx
- src/app/matching/mate-details/[postId]/layout.tsx
- src/app/matching/mate-details/[postId]/revise/page.tsx
- src/app/matching/mate-new-post/page.tsx
- src/app/matching/team-details/[postId]/application/page.tsx
- src/app/matching/team-details/[postId]/layout.tsx
- src/app/matching/team-details/[postId]/revise/page.tsx
- src/app/matching/team-new-post/page.tsx
> #175 매칭 페이지 에러 처리

- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
> #178 기타 버그 수정

- src/app/community/[tag]/page.tsx
- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
- src/app/community/components/commentList.tsx
- src/app/components/UserProfile.tsx
- src/services/user/getOtherUserData.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능).
- 유저 프로필 보려면 로그인이 필요하게끔 만들었습니다.
> #161 community api

- src/app/map/components/CourtReport.tsx
- src/types/basketballCourt/basketballCourtReport.ts
> 농구장 제보하기 타입 수정 완료했습니다. BasketballCourtReport 파일에 주석으로 default 값 명시해놨습니다.
> #108 refactor: 농구장 제보하기 타입 수정

- src/app/map/components/CourtDetails.tsx
- src/services/basketballCourt/getCourtDetails.ts
- src/types/basketballCourt/basketballCourtsDetails.ts
> 농구장 시설 채팅 연결
> 시설 채팅 구별을 위해서 제목 필요
> 현재 시설 채팅 누르면 리스트에 같은 시설 채팅이 여러개 보이는거 같은데 테스트 확인 부탁드립니다.
> #184 농구장 시설 채팅 연결

- src/app/matching/mate-details/[postId]/application/page.tsx
- src/app/matching/team-details/[postId]/application/page.tsx
> #178 지원하기 필수 필드 추가

- src/app/map/components/CourtDetails.tsx
- src/app/map/components/CourtDetailsFull.tsx
- src/app/map/components/CourtReport.tsx
- src/app/map/components/CourtReportDetails.tsx
- src/app/map/components/KakaoMap.tsx
- src/services/basketballCourt/getReportCourtDetails.ts
- src/services/basketballCourt/getReportCourts.ts
- src/types/basketballCourt/basketballCourtReport.ts
> 농구장 제보 검토 마커 추가 완료했습니다. react-query refetch로 제보 완료 후 바로 정보 업데이트해 마커 보이게 구현했습니다.
<img
src="https://github.com/SlamTalk/slam-talk-frontend/assets/103404125/ca99674b-1dc2-4a52-abaf-600bf66995ec"
width="40%"
/>
> 호버시 농구장 제목 표시
> #184 농구장 제보 검토 마커 추가, 타입 업데이트, 모달 알림

- src/app/admin/components/AdminCourtDetails.tsx
> 관리자 페이지 승인시 body 데이터 수정

- src/app/layout.tsx
- src/app/map/components/KakaoMap.tsx
> 지도 마커 클러스터 추가
> 사용자가 제보해 검토중인 마커는 구별을 위해 클러스터에서 분리했습니다.
> #188 feat: 지도 마커 클러스터 추가

- src/app/(auth)/login/email/page.tsx
- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/my-page/settings/page.tsx
- src/app/(auth)/signup/page.tsx
- src/app/(auth)/social-login/page.tsx
- src/app/api/axiosInstance.ts
- src/app/community/article/[id]/page.tsx
> 'https://www.slam-talk.site/' 으로 도메인 변경 완료하며 환경 변수 변경 완료했습니다.
> #199 refactor: 도메인 변경에 따른 환경 변수 변경

- src/app/(auth)/find-password/layout.tsx
- src/app/(auth)/find-password/page.tsx
> 현재 api 비밀번호 변경은 개발되었는데 '비밀번호 찾기(재설정)'는 개발되지 않아 개발 전까지 이슈 close 하려고 합니다. 원래 제가 의도했던건 자체 로그인시 비밀번호를 까먹으면 비밀번호 찾기를 하는 로직이었는데 현재 마이페이지에서 본인 비밀번호 변경하는 api만 개발 완료되어서 추후 회의를 통해 반영하겠습니다.
> #192 비밀번호 찾기 페이지 style 수정

- src/app/(auth)/login/page.tsx
> #199 소셜로그인 환경변수 변경

- README.md
> README.md 추가
**main에 develop 반영시 README.md 파일이 달라 충돌**이 납니다. 앞으로 각자 readme 고치는 브랜치를 파고 develop에 PR 보내서 먼저 README.md 고친 다음 메인에도 PR을 보내서 반영하는 방법이 좋을 것 같은데 어떻게 생각하시나요?
리드미에 들어갈 사진 찍으려고 메인에 PR 보냅니다. 사진은 수욜까지 반영이 되면 좋을 것 같습니다.
이 PR 머지 후 충돌 사라지면 이전 PR도 머지하겠습니다.
> #211 docs: README.md 추가

- README.md
> #223 docs: README.md 주요 기능 사진 추가

- README.md
> #223 docs: README.md 수정(프로젝트 소개, 전체 구조)

- README.md
> 리드미 업데이트
- 👀 같이 리뷰 필요
> 개발 기간이 서비스 소개에 들어가 있는게 이상해서 밑으로 내렸습니다. 아니면 아예 삭제해도 좋을 것 같아요.
> @SwimmingRiver  수영님 소켓 주소라고 써놨는데 고칠 필요 있으면 수정해주세요~
> docs: 환경 변수 주소 추가, 문서 위치 변경

- README.md
> @SwimmingRiver 님 깃허브 오타 수정했습니다
> docs: 오타 수정

- src/app/community/[tag]/page.tsx
- src/app/community/article/[id]/page.tsx
- src/services/community/getCommunityArticle.ts
- src/services/community/getCommunityBoard.ts
- src/services/community/getCommunityTag.ts
> 커뮤니티 페이징 기능 추가
- 현재 페이지 당 10 개로 했는데, 생각보다 여백이 많이 생겨서 스타일 수정하면서 조정하겠습니다.
- 태그별 게시판 api 안쓰려고 했는데, 페이지 수가 각각 달라서 api 요청이 필요해서 사용했습니다.
> #208 feature: 커뮤니티 페이징 추가

- src/app/community/[tag]/page.tsx
- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
- src/app/community/components/commentList.tsx
- src/app/community/write/page.tsx
- src/services/community/getCommunityTag.ts
> 커뮤니티 스타일 조정
++++ 추가 사항
<div>
width="260px" />
width="260px" />
</div>
- 추가 수정할 필요한 부분 있으면 말씀해주세요!
> #232 커뮤니티 스타일 조정

- .gitignore
- src/app/(auth)/my-page/profile/page.tsx
- src/app/community/[tag]/page.tsx
- src/app/map/components/CourtReport.tsx
- src/app/map/components/KakaoMap.tsx
> 농구장, 커뮤니티 하단 버튼 동기님 코드(매칭 하단 버튼) 참고해서 반응형 고쳤습니다.
> 크롬, 사파리 환경에서 확인 완료했습니다.
수정 전 
수정 후
- 👀 같이 리뷰 필요
1. classname이랑 style 혼재해서 사용한 부분들이 있는데 모두 tailwindcss 맞추는거 어떨까요? 
저는 style 모두 확인하고 tailwindcss로 맞춰놨습니다. 이 부분 확인 부탁드립니다.
2. 추가로 tailwindcss 중복 방지, 오류 검사를 위해 VSCODE 확장 프로그램 Tailwind CSS IntelliSense 설치 안하신 분 설치 추천합니다!!
+ AI 툴(Cursor, Tabnine) 등도 생산성 향상으로 추천합니다.
> # 249 농구장 지도, 커뮤니티 하단 버튼 반응형 수정

- src/app/(auth)/find-password/layout.tsx
- src/app/(auth)/login/email/page.tsx
- src/app/(auth)/login/layout.tsx
- src/app/(auth)/my-page/mate-matching-list/page.tsx
- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/my-page/profile/page.tsx
- src/app/(auth)/my-page/settings/change-password/page.tsx
- src/app/(auth)/my-page/settings/page.tsx
- src/app/(auth)/my-page/team-matching-list/page.tsx
- src/app/(auth)/signup/components/EmailValidation.tsx
- src/app/(auth)/signup/components/NicknamePassword.tsx
- src/app/page.tsx
- src/styles/globals.css
> Enter key event 추가하고 기존 event type 명시, 함수 분리 리팩토링 완료했습니다.
> Next UI에서만 focus시 primary 컬러 적용되는 부분 전역에서 적용되도록 설정했습니다. (크롬에서만 일단 정상 적용됩니다.)
> key event 추가하면 좋은 부분 다 추가하면 좋을 것 같습니다!
> #251 Enter key event 추가, 리팩토링, focus color 일관화

- src/app/chatting/components/messageList.tsx
소켓 통신으로 전송한 메시지는 시간이 표시되지않는 부분 수정
> #240 전송시 메시지 시간오류 수정

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
> 채팅 과거내역 불러오기 api 변경된 부분 테스트 하려고 추가요청 부분 잠시 주석처리 했습니다.
> test: 추가 요청부분 주석처리

- src/app/chatting/chatroom/[roomId]/page.tsx
> 농구장 시설 채팅방 최초 접속시 소켓연결이 안되는 경우 오류 때문에 요청 순서 변경했습니다.
> fix: 채팅 소켓 연결 순서 변경

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/matching/mate-details/[postId]/page.tsx
> 채팅이 정상 작동하지않는 부분 오류 해결
- 농구장 채팅방 api 요청 순서 변경하여 해결
- 시설 채팅방만 토큰이 발급되지않아 소켓 연결 실패된 부분 파악 -> 토큰 생성시 소켓 연결 재요청하게 변경
> #240 매칭시 채팅 오류 해결

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/components/messageList.tsx
>기존 버튼으로 작동하던 부분을 상단 스크롤에 도달했을 때 추가 요청하도록 수정했습니다.
infiniteQuery랑 api 구조랑 맞지않는 것 같아서 사용하지 않았습니다.
> #240 채팅 메시지 추가 요청 스크롤 이벤트로 수정

- src/app/components/Footer.tsx
> #266 푸터 선택된 탭 아이콘 색상 반전

- src/app/matching/mate-details/[postId]/application/page.tsx
- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
> #274 지원하기 버그 수정, 코드 리팩토링

- src/app/chatting/components/messageList.tsx
- src/app/chatting/list/page.tsx
- src/app/chatting/page.tsx
- src/app/components/Footer.tsx
> 채팅 목록 리팩토링
> 수정 후 스크린샷
- 👀 같이 리뷰 필요 (선택)
> 채팅 종류 구분을 위해서 이미지를 어떻게 줘야할까요?
https://w1704261477-g9r158782.slack.com/archives/C06C8DE6Z5Z/p1714548221818879
> #281 채팅 목록 리팩토링

- src/app/community/article/[id]/page.tsx
- src/app/community/write/page.tsx
> #283 커뮤니티 이미지 크게 보기 추가

- src/app/matching/components/MateMatching.tsx
- src/app/matching/components/TeamMatching.tsx
- src/app/matching/page.tsx
> #287 매칭 페이지 탑 버튼

- src/app/map/components/KakaoMap.tsx
> #288 참고해서 스카이뷰 버튼이 눌리지 않는 같은 문제가 있어 수정 완료했습니다.
> #289 kakao map 스카이뷰 버튼 눌리지 않는 버그 수정

- src/app/components/header/Header.tsx
- src/app/components/header/NotificationIcon.tsx
- src/app/components/header/Notifications.tsx
- src/app/map/components/CourtDetails.tsx
- src/app/map/components/KakaoMap.tsx
- src/services/notifications/getNotifications.ts
> 알림 기본 연결 작업만 해놨습니다. 추후 타입 추가 등 발전 예정입니다.
> 작은 스타일링 수정이라 같이 포함시켰습니다.
> - 농구장 x close 버튼 스타일 수정
> - 농구장 제보 버튼 높이 맞추기
> #273 헤더에 알림 아이콘 추가

- src/app/(auth)/find-password/page.tsx
- src/app/(auth)/my-page/settings/change-password/page.tsx
- src/app/(auth)/signup/components/EmailValidation.tsx
- src/utils/validations.ts
> 비밀번호 찾기, 재설정 API 연결 완료했습니다.
- 👀 같이 리뷰 필요
> 현재 백엔드에서 비밀번호 찾기('/find-password' 페이지)에서 슬램톡 유저인지 검증은 불필요하다고 안하신다고 하고 소셜 로그인 계정에 대한 처리 업데이트 예정이라고 합니다.
> 비밀번호 재설정, 변경시 프론트/백엔드간 특수문자 정규표현식이 달라서 오류가 발생하는데 백엔드에서 업데이트 예정입니다.
> 위에 언급한 이슈들 백엔드도 업데이트 완료되면 해당 PR 머지하겠습니다!
resolved: #298
> #298 비밀번호 찾기, 재설정 API 연결

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/community/[tag]/page.tsx
- src/app/community/article/[id]/[edit]/page.tsx
- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
- src/app/community/components/commentList.tsx
- src/app/community/write/page.tsx
- 댓글 수는 api 완성되는 대로 바로 추가하겠습니다.
> #285 게시물 작성 페이지 수정 

- src/app/(auth)/my-page/mate-matching-list/page.tsx
- src/app/(auth)/my-page/page.tsx
- src/app/(auth)/my-page/team-matching-list/page.tsx
- src/services/user/getMyMateMatchingData.ts
- src/services/user/getMyTeamMatchingData.ts
- src/types/matching/mateDataType.ts
- src/types/matching/teamDataType.ts
- 일단 간단하게만 붙여놨고, 영어로 표시되는 부분들 한글로 수정 및 스타일 수정할 예정입니다.
> #293 메이트 찾기/상대팀 찾기 내역 확인 페이지

- src/app/chatting/chatroom/[roomId]/page.tsx
> #240 채팅방 에러 해결

- src/app/community/[tag]/page.tsx
- src/types/community/board.ts
> 게시글 댓글 수 추가 했습니다.
다른 색상으로 하려니 hover 가 따로 적용돼서 제목 색상이랑 같게 했습니다.
> #285 게시글 댓글 수 추가

- src/app/components/header/Notifications.tsx
> 알림 읽음, 삭제 바로 반영 코드 추가했습니다.
> 채팅 알림 클릭시 채팅방으로 이동에서 -> 채팅 목록으로 이동으로 uri 백엔드에서 현재 수정중입니다.
> #273 알림 읽음, 삭제 바로 반영

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/chatting/list/page.tsx
> #240 채팅 로그인 제한

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/components/Footer.tsx
> footer에 안읽은 메시지 추가
- 표시를 넣으니까 글자가 안보여서 아이콘 크기를 같이 줄였습니다.
> footer에 안읽은 메시지 추가

- src/app/admin/components/AdminUserAvatar.tsx
- src/app/admin/page.tsx
- src/app/components/header/Notifications.tsx
- src/app/components/header/NotificationsUserAvatar.tsx
- src/app/components/loading/SmallLoading.tsx
> 채팅 알림은 백엔드에서 userId 넘겨주기가 어렵다고 해서 Footer에서 쓰이는 채팅 아이콘을 Avatar에 활용했습니다.
> 현재 백엔드 알림 진행된 부분 참고해서 스타일링 마무리 완료했습니다.
- 👀 같이 리뷰 필요
빨간색 동그라미가 있는 알림이 안읽은 알림입니다. 이 동그라미 추후 채팅 아이콘 푸터 옆에도 newMsg있으면 넣으면 좋을 것 같아요!
> #273 인앱 알림 스타일링 완료, 개별 삭제 연결

- .eslintrc.json
- src/app/chatting/chatroom/[roomId]/page.tsx
> #319 채팅방 로딩 추가

- src/app/chatting/chatroom/[roomId]/page.tsx
- src/app/components/Footer.tsx
> 오늘 총미님하고 회의하면서 수정한 부분입니다.
- footer 안읽은 표시 크기 조정
- 채팅 refetch 위치 조정
> 채팅 관련 리팩토링

- src/app/admin/components/AdminCourtDetails.tsx
> #277 거절 로직 추가

- src/app/chatting/list/page.tsx
> API 응답 전 로딩 추가 완료했습니다.
resolved: #319
> #319 채팅 목록 로딩 추가

- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능).
resolved #286
> #286 상세 페이지 상세 내용 줄바꿈 출력 안되는 문제 수정

- src/app/matching/mate-details/[postId]/page.tsx
- src/app/matching/team-details/[postId]/page.tsx
전반적으로 봤을 때 이상한 부분들 매끄럽게 수정했습니다!
> #331 매칭 게시글 날짜 표시 및 기타 스타일 수정

- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
- src/app/community/write/page.tsx
> 댓글 관련 스타일 조정
- 댓글 수정/삭제 버튼 간격 조정
- 모달 메시지 변경
> 댓글 관련 스타일 조정

- src/app/community/article/[id]/page.tsx
- src/app/components/Footer.tsx
> 커뮤니티 모바일 브라우저에서 댓글 작성되지 않는 이슈 
##
바로 develop으로 머지하겠습니다.
> 커뮤니티 모바일 환경 댓글 작성 에러 수정

- src/app/community/article/[id]/page.tsx
- src/app/community/components/commentItem.tsx
- src/app/community/components/commentList.tsx
> #338 모바일 브라우저 환경에서 댓글 작성 오류 수정

- src/app/chatting/list/page.tsx
- src/app/chatting/page.tsx
> 채팅 리스트 loading 개선
> 1. 로그아웃 상황시 로그인 알림, 새로고침 후에도 항상 같은 동작 확인
> 2. 로그인 상황 로딩, 채팅 목록
> 3. 로그인 상황 채팅 목록 없을시
>
> 위 세가지 상황에서 로딩 제대로 도는 동작 확인 완료했습니다. 수정해야 할 부분 있으면 말씀해 주세요~
> #341 fix: 채팅 리스트 loading 개선

- src/app/layout.tsx
> google search console 인증 테스트
> #350 google search console 인증
